### ISSUE TITLE
Make crash

### ISSUE THREAD

**Issue by Axxon** [VCVRack/AudibleInstruments#19]
Hello, and first thanks you for your work, it's amazing. I've got a crash after ```git submodule update --init --recursive``` and ```make```.
```
Rack/plugins/AudibleInstruments  master ✗                                                                       3d ◒  
▶ make
g++ -fshort-enums -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Frames.cpp.o src/Frames.cpp
In file included from src/Frames.cpp:4:0:
./eurorack/frames/poly_lfo.h:78:49: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   inline const uint16_t dac_code(uint8_t index) const {
                                                 ^
src/Frames.cpp: In constructor ‘FramesWidget::FramesWidget()’:
src/Frames.cpp:319:11: error: ‘createValueLight’ was not declared in this scope
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(30, 101), &module->outputs[Frames::GAIN1_LIGHT + 0].
           ^
src/Frames.cpp:319:39: error: ‘GreenRedPolarityLight’ was not declared in this scope
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(30, 101), &module->outputs[Frames::GAIN1_LIGHT + 0].
                                       ^
src/Frames.cpp:319:39: error: template argument 1 is invalid
src/Frames.cpp:320:39: error: the value of ‘GreenRedPolarityLight’ is not usable in a constant expression
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(97, 101), &module->outputs[Frames::GAIN1_LIGHT + 1].
                                       ^
src/Frames.cpp:319:39: note: ‘GreenRedPolarityLight’ was not declared ‘constexpr’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(30, 101), &module->outputs[Frames::GAIN1_LIGHT + 0].
                                       ^
src/Frames.cpp:320:39: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(97, 101), &module->outputs[Frames::GAIN1_LIGHT + 1].
                                       ^
src/Frames.cpp:320:39: note:   expected a type, got ‘GreenRedPolarityLight’
src/Frames.cpp:321:39: error: the value of ‘GreenRedPolarityLight’ is not usable in a constant expression
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(165, 101), &module->outputs[Frames::GAIN1_LIGHT + 2]
                                       ^
src/Frames.cpp:319:39: note: ‘GreenRedPolarityLight’ was not declared ‘constexpr’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(30, 101), &module->outputs[Frames::GAIN1_LIGHT + 0].
                                       ^
src/Frames.cpp:321:39: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(165, 101), &module->outputs[Frames::GAIN1_LIGHT + 2]
                                       ^
src/Frames.cpp:321:39: note:   expected a type, got ‘GreenRedPolarityLight’
src/Frames.cpp:322:39: error: the value of ‘GreenRedPolarityLight’ is not usable in a constant expression
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(232, 101), &module->outputs[Frames::GAIN1_LIGHT + 3]
                                       ^
src/Frames.cpp:319:39: note: ‘GreenRedPolarityLight’ was not declared ‘constexpr’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(30, 101), &module->outputs[Frames::GAIN1_LIGHT + 0].
                                       ^
src/Frames.cpp:322:39: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(232, 101), &module->outputs[Frames::GAIN1_LIGHT + 3]
                                       ^
src/Frames.cpp:322:39: note:   expected a type, got ‘GreenRedPolarityLight’
src/Frames.cpp:323:40: error: the value of ‘GreenRedPolarityLight’ is not usable in a constant expression
  addChild(createValueLight<MediumLight<GreenRedPolarityLight>>(Vec(61, 155), &module->outputs[Frames::EDIT_LIGHT].valu
                                        ^
src/Frames.cpp:319:39: note: ‘GreenRedPolarityLight’ was not declared ‘constexpr’
  addChild(createValueLight<SmallLight<GreenRedPolarityLight>>(Vec(30, 101), &module->outputs[Frames::GAIN1_LIGHT + 0].
                                       ^
src/Frames.cpp:323:40: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::MediumLight’
  addChild(createValueLight<MediumLight<GreenRedPolarityLight>>(Vec(61, 155), &module->outputs[Frames::EDIT_LIGHT].valu
                                        ^
src/Frames.cpp:323:40: note:   expected a type, got ‘GreenRedPolarityLight’
../../compile.mk:53 : la recette pour la cible « build/src/Frames.cpp.o » a échouée
make: *** [build/src/Frames.cpp.o] Erreur 1
x                                                                                                             3d ◒  ⍉⍉
```
I'm not already a C++ dev and i'm not in the project but i can immagine that the GreenRedPolarityLight constant is not defined in the variable scope. Somebody can help ?

**Comment by AndrewBelt** [comment]
This repo is not in a buildable state right now.

**Comment by Axxon** [comment]
So i can't have this plug on ubuntu ? cause "refresh plugin" with ui fails.

**Comment by AndrewBelt** [comment]
Not in its current state, no. "Refresh Plugin" only works on Rack v0.4. You can use it, you just have to find a date (say, three days ago) when it compiled, and check out commits from that day in all the VCV repos.

**Comment by Axxon** [comment]
Ok i tried to checkout earlier, don't work. Don't know why the crew don't made a dev branch.. I will try later. thx

**Comment by AndrewBelt** [comment]
"The crew" is me, and I'm too lazy at the moment. Maybe in a bit.

**Comment by Axxon** [comment]
Eheh so it's a honnor for me to speak with a great maker !

**Comment by crafter312** [comment]
I just had a similar crash when trying to make the plugin. It was almost finished making the entire plugin, but it crashed in Warps.cpp

`g++ -fshort-enums -DTEST -I./eurorack -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/Warps.cpp.o src/Warps.cpp
src/Warps.cpp: In constructor 'WarpsWidget::WarpsWidget()':
src/Warps.cpp:160:3: error: 'RedGreenBlueLight' was not declared in this scope
   RedGreenBlueLight *algorithmLight = new RedGreenBlueLight();
   ^~~~~~~~~~~~~~~~~
src/Warps.cpp:160:22: error: 'algorithmLight' was not declared in this scope
   RedGreenBlueLight *algorithmLight = new RedGreenBlueLight();
                      ^~~~~~~~~~~~~~
src/Warps.cpp:160:43: error: expected type-specifier before 'RedGreenBlueLight'
   RedGreenBlueLight *algorithmLight = new RedGreenBlueLight();
                                           ^~~~~~~~~~~~~~~~~
make: *** [../../compile.mk:54: build/src/Warps.cpp.o] Error 1`

It crashed almost right away when I tried to make it a couple days ago, but it didn't crash as much now.

**Comment by AndrewBelt** [comment]
This has been fixed, `git pull` Rack and its plugins and rebuild.
